name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
env:
  ATMOS_VERSION: 1.170.0
jobs:
  atmos-affected:
    runs-on: ubuntu-latest
    steps:
      - id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v6
        with:
          atmos-config-path: ./
          atmos-version: ${{ env.ATMOS_VERSION }}
          # nested-matrices-count: 2
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}
          # default-branch: ${{ github.event.pull_request.head.ref }}

    outputs:
      stacks: ${{ steps.affected.outputs.matrix }}
      has-affected-stacks: ${{ steps.affected.outputs.has-affected-stacks }}

  atmos-plan:
    needs: ["atmos-affected"]
    if: ${{ needs.atmos-affected.outputs.has-affected-stacks == 'true' }}
    name: Plan (${{ matrix.name }})
    secrets: inherit
    uses: ./.github/workflows/atmos-terraform-plan-matrix.yaml
    strategy:
      matrix: ${{ fromJson(needs.atmos-affected.outputs.stacks) }}
      max-parallel: 1 # This is important to avoid ddos GHA API
      fail-fast: false # Don't fail fast to avoid locking TF State
    with:
      stacks: ${{ matrix.items }}
      atmos-version: "1.167.0"
      sha: ${{ github.event.pull_request.head.sha }}
      atmos-config-path: ./
