name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
env:
  ATMOS_VERSION: 1.167.0
jobs:
  atmos-affected:
    runs-on: ubuntu-latest
    steps:
      - id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v6
        with:
          atmos-config-path: ./
          atmos-version: ${{ env.ATMOS_VERSION }}
          nested-matrices-count: 2
          # default-branch: ${{ github.event.pull_request.head.ref }}

    outputs:
      matrix: ${{ steps.affected.outputs.matrix }}
      has-affected-stacks: ${{ steps.affected.outputs.has-affected-stacks }}

  atmos-plan:
    needs: ["atmos-affected"]
    if: ${{ needs.atmos-affected.outputs.has-affected-stacks == 'true' }}
    name: Plan ${{ matrix.stack_slug }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix: ${{ fromJson(needs.atmos-affected.outputs.matrix) }}
    ## Avoid running the same stack in parallel mode (from different workflows)
    concurrency:
      group: ${{ matrix.stack_slug }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup atmos
        uses: cloudposse/github-action-setup-atmos@v2
        with:
          atmos-version: ${{ env.ATMOS_VERSION }}
      - name: Cache .terraform
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./components/terraform/${{ matrix.component }}/.terraform/providers
          key: ${{ hashFiles(format('./components/terraform/{0}/provider.tf', matrix.component )) }}
      - name: Run plan
        shell: bash
        run: |
          set +e
          atmos terraform plan ${{ matrix.component }} \
          --stack ${{ matrix.stack }} \
          -out ${PWD}/${{ matrix.component }}_${{ matrix.stack }}.tfplan \
          -lock=false \
          -input=false \
          -no-color
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.component }}_${{ matrix.stack }}_plan
      #     path: ${{ matrix.component }}_${{ matrix.stack }}.tfplan
      #     retention-days: 1
  atmos-apply:
    needs: ["atmos-affected", "atmos-plan"]
    if: ${{ needs.atmos-affected.outputs.has-affected-stacks == 'true' }}
    name: Apply ${{ matrix.stack_slug }}
    runs-on: ubuntu-latest
    environment:
      name: apply
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix: ${{ fromJson(needs.atmos-affected.outputs.matrix) }}
    ## Avoid running the same stack in parallel mode (from different workflows)
    concurrency:
      group: ${{ matrix.stack_slug }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup atmos
        uses: cloudposse/github-action-setup-atmos@v2
        with:
          atmos-version: ${{ env.ATMOS_VERSION }}
      # - name: download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ matrix.component }}_${{ matrix.stack }}_plan
      - name: Cache .terraform
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./components/terraform/${{ matrix.component }}/.terraform/providers
          key: ${{ hashFiles(format('./components/terraform/{0}/provider.tf', matrix.component )) }}
      - name: Run apply
        shell: bash
        run: |
          set +e
          atmos terraform apply ${{ matrix.component }} \
          --stack ${{ matrix.stack }} \
          -auto-approve \
          -input=false \
          -no-color
